### 1. Listar Prestadores (Para pegar um ID válido)
GET http://localhost:3333/providers

### 2. Criar uma Transação (Substitua o ID_DO_PRESTADOR pelo ID que veio acima)
POST http://localhost:3333/transactions
Content-Type: application/json

{
  "amount": 5000,
  "providerId": "60defd69-6361-4d7c-aaa5-b21222b58e42", 
  "description": "Serviço de Teste",
  "category": "PINTURA",
  "state": "SP"
}
### 3. SIMULAR IUGU (Webhook de Pagamento)
POST http://localhost:3333/webhooks/iugu
Content-Type: application/json

{
  "event": "invoice.status_changed",
  "data": {
    "id":"API_INV_1770040608797",
    "status": "paid"
  }
}
### 4. Consultar Saldo do Prestador
# Substitua o ID abaixo pelo ID do prestador que você usou nas vendas
GET http://localhost:3333/providers/60defd69-6361-4d7c-aaa5-b21222b58e42/balance